//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanKhach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoanKhach()
        {
            this.DSKhachTheoDoans = new HashSet<DSKhachTheoDoan>();
            this.NhanVienTheoDoan = new HashSet<NhanVienTheoDoan>();
            this.KhachSanTheoDoan = new HashSet<KhachSanTheoDoan>();
            this.PhuongTienTheoDoan = new HashSet<PhuongTienTheoDoan>();
            this.ChiPhiKhacTheoDoans = new HashSet<ChiPhiKhacTheoDoan>();
            this.TienAnTheoDoan = new HashSet<TienAnTheoDoan>();
        }
    
        public int Id { get; set; }
        public string TenGoi { get; set; }
        public System.DateTime NgayKhoiHanh { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int TourId { get; set; }
        public int SLCho { get; set; }
        public int TongChiPhi { get; set; }
        public bool isEdit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSKhachTheoDoan> DSKhachTheoDoans { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVienTheoDoan> NhanVienTheoDoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSanTheoDoan> KhachSanTheoDoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuongTienTheoDoan> PhuongTienTheoDoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiKhacTheoDoan> ChiPhiKhacTheoDoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienAnTheoDoan> TienAnTheoDoan { get; set; }
    }
}
