//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusAndModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<LoaiDL> LoaiDLs { get; set; }
        public virtual DbSet<GiaTour> GiaTours { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
        public virtual DbSet<CTTour> CTTours { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<DoanKhach> DoanKhaches { get; set; }
        public virtual DbSet<NhiemVu> NhiemVus { get; set; }
        public virtual DbSet<DSKhachTheoDoan> DSKhachTheoDoans { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhanVienTheoDoan> NhanVienTheoDoans { get; set; }
        public virtual DbSet<KhachSanTheoDoan> KhachSanTheoDoans { get; set; }
        public virtual DbSet<PhuongTienTheoDoan> PhuongTienTheoDoans { get; set; }
        public virtual DbSet<ChiPhiKhacTheoDoan> ChiPhiKhacTheoDoans { get; set; }
        public virtual DbSet<TienAnTheoDoan> TienAnTheoDoans { get; set; }
    }
}
